modLoader = "javafml"
loaderVersion = "[37,)"
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups"
version = "${file.jarVersion}"
displayName = "FTB Backups"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-backups"
logoFile = "logo.png"
authors = "LatvianModder"
description = '''
Creates backups of your world
'''

[[dependencies.ftbbackups]]
modId="forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side="BOTH"

[[dependencies.ftbbackups]]
modId="minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side="BOTH"
