modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups"
version = "${version}"
displayName = "FTB Backups"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-backups"
logoFile = "logo.png"
authors = "FTB Team"
description = '''
Creates backups of your world'''

[[dependencies.ftbbackups]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.ftbbackups]]
#modId="minecraft"
#mandatory = true
#versionRange = "[1.21,)"
#ordering = "NONE"
#side="BOTH"
